apiVersion : apps/v1
kind: Deployment
metadata:
  name: myappfrontend 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myappfrontend
  template:
    metadata:
      labels:
        app: myappfrontend 
    spec:
      containers:
        - name: myappfrontend 
          imagePullPolicy: Always
          image: pratheekacrcapstone.azurecr.io/myappfrontend:latest
          ports:
          - containerPort: 80